# Generated by Django 4.0.5 on 2022-09-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_blog',
            name='date',
            field=models.DateField(default='1967-10-10'),
        ),
        migrations.AddField(
            model_name='project_blog',
            name='description',
            field=models.TextField(default='DEFAULT VALUE', max_length=2000),
        ),
    ]
