# Generated by Django 4.0.5 on 2022-09-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project_blog_date_project_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_blog',
            name='date',
            field=models.DateField(default='2020-10-10'),
        ),
    ]
